language: python

python: 2.7

services:
    - rabbitmq
    - redis-server

install:
    - pip install -r requirements.txt

before_script:
    - cp config/config.xml.dist config/config.xml

script: nosetests

after_script:
    - pip install scrutinizer-ocular
    - ocular --data-file ".coverage" --config-file ".coveragerc"
