language: python
python: 2.7
sudo: false

services:
    - rabbitmq
    - redis-server

install:
    - pip install -r requirements.txt

before_script:
    - cp config/config.xml.dist config/config.xml
    - celery worker -A worker.event -n event -Q event --loglevel=INFO --broker=amqp://guest:guest@localhost:5672/ &
    - celery worker -A worker.recommend -n recommend -Q recommend --loglevel=INFO --broker=amqp://guest:guest@localhost:5672/ &

script: nosetests

after_script:
    - pip install scrutinizer-ocular
    - ocular --data-file ".coverage" --config-file ".coveragerc"
